apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: iot-system
data:
  AWS_REGION: "${AWS_REGION}"
  DB_HOST: "${RDS_ENDPOINT}"
  DB_NAME: "iotdb"
  DB_USER: "iotuser"
  DB_SECRET_ARN: "${SECRET_ARN}"
  MQTT_HOST: "${IOT_ENDPOINT}"
