apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secret-provider
  namespace: iot-system
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "${SECRET_ARN}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: "password"
  secretObjects:
  - secretName: db-secret
    type: Opaque
    data:
    - objectName: password
      key: password