apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: iot-system
type: Opaque
data:
  username: aW90dXNlcg==  # base64 encoded 'iotuser'
  password: aW90cGFzc3dvcmQ=  # base64 encoded 'iotpassword'